### ISSUE TITLE
ERROR: generate_reduced is not defined

### ISSUE THREAD

**Issue by linh47** [aiengineer/NUSCCF#4]
Hi,I found an error when I run the main.py in Pycharm2019,I have installed sklearn,pandas,matplotlib.My Python version is Python37
Can anyone tell me what's wrong?Thank you for sharing the codes.

The logs are followed.

count    100000.000000
mean          3.529860
std           1.125674
min           1.000000
25%           3.000000
50%           4.000000
75%           4.000000
max           5.000000
Name: rating, dtype: float64
       user_id  item_id  rating
22496        1       68       4
13638        1      129       5
34165        1       75       4
5682         1       49       3
18695        1      161       4
       user_id  item_id  rating
70539        1        7       4
9170         1       14       5
75385        1      198       5
38697        1      136       3
47539        1      178       5
{1: [68, 129, 75, 161, 224, 81, 82, 9, 115, 108, 28, 134, 228, 95, 199, 163, 61, 156, 222, 111, 251, 206, 513, 83, 242, 286, 778, 178, 483, 604, 863, 740, 673, 28, 48, 511, 488, 213, 135, 923], 640: [919, 174, 
…………………………………………………………………………………………………………………………
231, 391, 595, 399, 450, 549, 139, 468, 724, 401, 412, 443, 97, 720]}
generating interesting reduced list...
**Traceback (most recent call last):
  File "C:/Users/linh/Desktop/NUSCCF-master/main.py", line 45, in <module>
    main()
  File "C:/Users/linh/Desktop/NUSCCF-master/main.py", line 24, in main
    NIU_reduced_list = generate_reduced(NIU)
interesting reduced list generated.
NameError: name 'generate_reduced' is not defined**
generating NIU reduced list...

**Comment by soran-ghaderi** [comment]
> Hi,I found an error when I run the main.py in Pycharm2019,I have installed sklearn,pandas,matplotlib.My Python version is Python37
> Can anyone tell me what's wrong?Thank you for sharing the codes.
> 
> The logs are followed.
> 
> count 100000.000000
> mean 3.529860
> std 1.125674
> min 1.000000
> 25% 3.000000
> 50% 4.000000
> 75% 4.000000
> max 5.000000
> Name: rating, dtype: float64
> user_id item_id rating
> 22496 1 68 4
> 13638 1 129 5
> 34165 1 75 4
> 5682 1 49 3
> 18695 1 161 4
> user_id item_id rating
> 70539 1 7 4
> 9170 1 14 5
> 75385 1 198 5
> 38697 1 136 3
> 47539 1 178 5
> {1: [68, 129, 75, 161, 224, 81, 82, 9, 115, 108, 28, 134, 228, 95, 199, 163, 61, 156, 222, 111, 251, 206, 513, 83, 242, 286, 778, 178, 483, 604, 863, 740, 673, 28, 48, 511, 488, 213, 135, 923], 640: [919, 174,
> …………………………………………………………………………………………………………………………
> 231, 391, 595, 399, 450, 549, 139, 468, 724, 401, 412, 443, 97, 720]}
> generating interesting reduced list...
> **Traceback (most recent call last): File "C:/Users/linh/Desktop/NUSCCF-master/main.py", line 45, in main() File "C:/Users/linh/Desktop/NUSCCF-master/main.py", line 24, in main NIU_reduced_list = generate_reduced(NIU) interesting reduced list generated. NameError: name 'generate_reduced' is not defined**
> generating NIU reduced list...

Hi amigo,
thanks for your helping, the issue has been corrected.
In case you encountered further problems please let me know and I will help you
